name: docs
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/docs.yml'
      - 'src/nvim/api/*.[ch]'
      - 'src/nvim/eval.lua'
      - 'runtime/lua/**.lua'
      - 'runtime/doc/**'
      - 'scripts/gen_vimdoc.py'
      - 'scripts/gen_help_html.lua'
jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
      pull-requests: write
    env:
      BIN_DIR: ${{ github.workspace }}/bin
      DOXYGEN_URL: 'https://github.com/doxygen/doxygen/releases/download/Release_1_10_0/doxygen-1.10.0.linux.bin.tar.gz'
      DOXYGEN_VERSION: 1.10.0
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-msgpack

      - uses: cachix/install-nix-action@v25
      - run: |
          nix-env -iA doxygen -f https://github.com/NixOS/nixpkgs/archive/9957cd48326fe8dbd52fdc50dd2502307f188b0d.tar.gz

      - name: Generate docs
        run: |
          make doc
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Job failed, run 'make doc' and commit your doc changes."
            echo "::error::The doc generation produces the following changes:"
            git diff --color --exit-code
          fi

      - name: Validate docs
        run: make lintdoc
